apiVersion: v1
kind: Service
metadata:
  name: spring-boot-app
spec:
  type: LoadBalancer
  selector:
    app: spring-boot-app
  ports:
    - port: 80
      targetPort: 8080  # Spring Boot default port

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mine
  labels:
    app: mine
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mine
  template:
    metadata:
      labels:
        app: mine
    spec:
      containers:
        - name: mine
          image: us-central1-docker.pkg.dev/GOOGLE_PROJECT/srishti/mine:latest
          ports:
            - containerPort: 8080  # Match Spring Boot port
